import type { SeedTask } from '@/types/task'

/** Placed relative to today, so the timeline always looks right on first open. */
export const SEED_TASKS: readonly SeedTask[] = [
  {
    title: 'Get React state management straight (useState / useReducer / Context)',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Read the "Managing State" section of the docs end to end.',
    offsetStart: -12,
    span: 5,
  },
  {
    title: 'Get comfortable with TypeScript generics and conditional types',
    category: 'Frontend',
    status: 'doing',
    priority: 'high',
    estimatedHours: 12,
    note: '10 easy + 10 medium problems from type-challenges.',
    offsetStart: -4,
    span: 10,
  },
  {
    title: 'Settle on REST API design and a shared error response shape',
    category: 'Backend',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 10,
    note: 'Which status code when, and one schema for every error body.',
    offsetStart: -1,
    span: 9,
  },
  {
    title: 'Learn to read SQL execution plans and index properly',
    category: 'Database',
    status: 'todo',
    priority: 'high',
    estimatedHours: 14,
    note: 'Read EXPLAIN output and tune three slow queries.',
    offsetStart: 3,
    span: 12,
  },
  {
    title: 'Build a local environment with Docker and docker compose',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 9,
    note: 'Go as far as shrinking the image with a multi-stage build.',
    offsetStart: 8,
    span: 8,
  },
  {
    title: 'Algorithm drills: binary search, DP, graphs',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'low',
    estimatedHours: 20,
    note: 'One problem each morning; read the solution after 25 minutes.',
    offsetStart: 0,
    span: 28,
  },
  {
    title: 'Run two full AWS SAA practice exams',
    category: 'Certification',
    status: 'todo',
    priority: 'high',
    estimatedHours: 16,
    note: 'Most points are lost on VPC and IAM, so focus there.',
    offsetStart: 16,
    span: 14,
  },
]
