import type { SeedTask } from '@/types/task'

/**
 * A ~15 month study plan, placed relative to today: negative offsets are the
 * past and are mostly finished, a handful straddle today and are in progress,
 * the rest are still ahead. Dates are derived from today when the seed is
 * expanded, so the timeline reads the same whenever it is first opened.
 */
export const SEED_TASKS: readonly SeedTask[] = [
  // Frontend
  {
    title: 'Write a page with semantic HTML and no div where a real element exists',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Run it through an outline checker afterwards.',
    offsetStart: -258,
    span: 3,
  },
  {
    title: 'Learn the box model and when margins collapse',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Reproduce three collapsing-margin surprises on purpose.',
    offsetStart: -254,
    span: 4,
  },
  {
    title: 'Make flexbox alignment automatic: justify, align, and the free-space rules',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Rebuild a navbar and a card row from memory.',
    offsetStart: -249,
    span: 5,
  },
  {
    title: 'Learn CSS Grid placement, auto-fit and minmax',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Build a responsive gallery with no media queries.',
    offsetStart: -243,
    span: 6,
  },
  {
    title: 'Understand specificity and the cascade',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Score ten selectors by hand before checking.',
    offsetStart: -236,
    span: 3,
  },
  {
    title: 'Learn CSS custom properties and where they beat a preprocessor variable',
    category: 'Frontend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Theme one component with them, light and dark.',
    offsetStart: -232,
    span: 4,
  },
  {
    title: 'Work through JavaScript scope, closures and the temporal dead zone',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Explain a counter factory out loud without notes.',
    offsetStart: -227,
    span: 6,
  },
  {
    title: 'Learn how this binds, and why arrow functions differ',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Predict the output of ten snippets before running them.',
    offsetStart: -220,
    span: 4,
  },
  {
    title: 'Get prototypes and the class desugaring straight',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Implement inheritance twice: prototypal, then with class.',
    offsetStart: -215,
    span: 5,
  },
  {
    title: 'Master map, filter, reduce and flatMap, and know when a loop reads better',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Rewrite ten loops as methods, then judge each one.',
    offsetStart: -209,
    span: 5,
  },
  {
    title: 'Learn destructuring, spread and default parameters properly',
    category: 'Frontend',
    status: 'done',
    priority: 'low',
    estimatedHours: 3,
    note: 'Refactor an old file where it genuinely helps.',
    offsetStart: -203,
    span: 3,
  },
  {
    title: 'Understand the event loop: macrotasks, microtasks and rendering',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Order a mixed setTimeout and Promise snippet on paper first.',
    offsetStart: -199,
    span: 6,
  },
  {
    title: 'Go from callbacks to Promises to async await, and know why each step happened',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Convert one callback-heavy module all the way forward.',
    offsetStart: -192,
    span: 6,
  },
  {
    title: 'Learn Promise.all, allSettled, race and any, and pick correctly',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Write a case where allSettled is the only right answer.',
    offsetStart: -185,
    span: 3,
  },
  {
    title: 'Learn the DOM API without a framework: query, create, delegate events',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Build a sortable table in plain JS.',
    offsetStart: -181,
    span: 6,
  },
  {
    title: 'Understand fetch, Request, Response and AbortController',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Cancel an in-flight request from a button.',
    offsetStart: -174,
    span: 4,
  },
  {
    title: 'Learn ES modules and what tree shaking can and cannot remove',
    category: 'Frontend',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Inspect a build output and find something that should have gone.',
    offsetStart: -169,
    span: 5,
  },
  {
    title: 'Start TypeScript: annotate an existing JS file and turn on strict',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'No any allowed, not even temporarily.',
    offsetStart: -163,
    span: 7,
  },
  {
    title: 'Learn unions, narrowing and discriminated unions',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Model a request state machine with one.',
    offsetStart: -155,
    span: 6,
  },
  {
    title: 'Learn generics: constraints, inference, and when not to reach for them',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 9,
    note: 'Write a typed result wrapper and a typed event emitter.',
    offsetStart: -148,
    span: 7,
  },
  {
    title: 'Work through conditional and mapped types',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Ten easy plus ten medium from type-challenges.',
    offsetStart: -140,
    span: 8,
  },
  {
    title: 'Reimplement the utility types: Pick, Omit, Partial, Record',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Write each from scratch before looking it up.',
    offsetStart: -131,
    span: 4,
  },
  {
    title: 'Understand branded types and when a nominal type earns its keep',
    category: 'Frontend',
    status: 'done',
    priority: 'low',
    estimatedHours: 4,
    note: 'Brand an id type and see what it catches.',
    offsetStart: -126,
    span: 3,
  },
  {
    title: 'Learn React fundamentals: JSX, props, and UI as a function of state',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Build it static first, then make it interactive.',
    offsetStart: -122,
    span: 7,
  },
  {
    title: 'Learn useState and decide which component owns each piece of state',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Lift state deliberately at least twice.',
    offsetStart: -114,
    span: 5,
  },
  {
    title: 'Learn lists and keys, and break one on purpose with an index key',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 3,
    note: 'Reorder a list and watch the inputs jump.',
    offsetStart: -108,
    span: 2,
  },
  {
    title: 'Learn useEffect as synchronisation, not as a lifecycle hook',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Remove three effects that were really derived state.',
    offsetStart: -105,
    span: 7,
  },
  {
    title: 'Learn useRef for values that should not trigger a render',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Store a timer id and clear it on unmount.',
    offsetStart: -97,
    span: 3,
  },
  {
    title: 'Learn useReducer and when it beats several useState calls',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Convert a form with interdependent fields.',
    offsetStart: -93,
    span: 4,
  },
  {
    title: 'Learn Context, and the re-render cost of putting too much in one',
    category: 'Frontend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Split a context in two and measure the difference.',
    offsetStart: -88,
    span: 4,
  },
  {
    title: 'Learn when memoisation helps, and prove it with the profiler',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Remove every memo that does not show up in a measurement.',
    offsetStart: -83,
    span: 5,
  },
  {
    title: 'Write custom hooks, and learn the rules of hooks by breaking them',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Extract two hooks from a component that got long.',
    offsetStart: -77,
    span: 4,
  },
  {
    title: 'Learn client-side routing: nested routes, params and redirects',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Build a two-page app with a shared layout route.',
    offsetStart: -72,
    span: 5,
  },
  {
    title: 'Learn controlled versus uncontrolled inputs and pick per case',
    category: 'Frontend',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Build the same form both ways and compare.',
    offsetStart: -66,
    span: 4,
  },
  {
    title: 'Learn form validation and how to show errors without being annoying',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Validate on blur and on submit, never on every keystroke.',
    offsetStart: -61,
    span: 4,
  },
  {
    title: 'Learn Tailwind properly: the utility model, variants, and when to extract',
    category: 'Frontend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Resist extracting a component until it repeats three times.',
    offsetStart: -56,
    span: 5,
  },
  {
    title: 'Build a dark mode that respects prefers-color-scheme and a manual toggle',
    category: 'Frontend',
    status: 'done',
    priority: 'low',
    estimatedHours: 5,
    note: 'Handle the flash of wrong theme on first paint.',
    offsetStart: -50,
    span: 4,
  },
  {
    title: 'Learn keyboard accessibility: focus order, focus traps and skip links',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Navigate the whole app without touching the mouse.',
    offsetStart: -45,
    span: 6,
  },
  {
    title: 'Learn ARIA roles and names, and the first rule of ARIA',
    category: 'Frontend',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Every interactive element gets a real accessible name.',
    offsetStart: -38,
    span: 5,
  },
  {
    title: 'Run a screen reader over the app and fix what is unreadable',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'One full pass with the eyes closed.',
    offsetStart: -32,
    span: 4,
  },
  {
    title: 'Learn Core Web Vitals: LCP, CLS and INP, and what moves each',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Measure before changing anything.',
    offsetStart: -27,
    span: 5,
  },
  {
    title: 'Learn image optimisation: formats, sizing, lazy loading, aspect ratio',
    category: 'Frontend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Kill every layout shift caused by an image.',
    offsetStart: -21,
    span: 4,
  },
  {
    title: 'Learn code splitting and route-level lazy loading',
    category: 'Frontend',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Check the bundle report before and after.',
    offsetStart: -16,
    span: 12,
  },
  {
    title: 'Learn browser caching headers from the frontend side',
    category: 'Frontend',
    status: 'doing',
    priority: 'low',
    estimatedHours: 4,
    note: 'Understand what a hashed filename actually buys.',
    offsetStart: -9,
    span: 14,
  },
  {
    title: 'Write component tests that assert behaviour, not markup',
    category: 'Frontend',
    status: 'doing',
    priority: 'high',
    estimatedHours: 8,
    note: 'Query by role and label, never by class name.',
    offsetStart: -4,
    span: 16,
  },
  {
    title: 'Learn Playwright and cover the three critical user journeys',
    category: 'Frontend',
    status: 'doing',
    priority: 'high',
    estimatedHours: 10,
    note: 'Stub the network so tests never hit a real service.',
    offsetStart: -2,
    span: 18,
  },
  {
    title: 'Learn state management beyond Context: when a store is actually justified',
    category: 'Frontend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Only after prop drilling has genuinely hurt.',
    offsetStart: 12,
    span: 14,
  },
  {
    title: 'Learn data fetching patterns: caching, revalidation, race conditions',
    category: 'Frontend',
    status: 'todo',
    priority: 'high',
    estimatedHours: 10,
    note: 'Reproduce a stale-response race, then fix it.',
    offsetStart: 24,
    span: 16,
  },
  {
    title: 'Learn Server Components and where the boundary actually falls',
    category: 'Frontend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 12,
    note: 'Build one page each way and compare the payloads.',
    offsetStart: 40,
    span: 20,
  },
  {
    title: 'Learn Web Components and shadow DOM well enough to decide against them',
    category: 'Frontend',
    status: 'todo',
    priority: 'low',
    estimatedHours: 6,
    note: 'Build one widget, note where styling gets awkward.',
    offsetStart: 62,
    span: 10,
  },

  // Backend
  {
    title: 'Learn HTTP methods and status codes, and stop returning 200 for errors',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Write down when each 4xx applies.',
    offsetStart: -256,
    span: 4,
  },
  {
    title: 'Learn request and response headers that actually matter day to day',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Content-Type, Accept, Cache-Control, Authorization.',
    offsetStart: -251,
    span: 3,
  },
  {
    title: 'Build a REST API with no framework to see what a framework does for you',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Routing and body parsing by hand, once.',
    offsetStart: -246,
    span: 6,
  },
  {
    title: 'Learn a web framework properly: middleware order and error handling',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Trace one request through every middleware.',
    offsetStart: -239,
    span: 5,
  },
  {
    title: 'Design a resource-oriented URL scheme and stick to it',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Nouns for paths, verbs for methods.',
    offsetStart: -233,
    span: 4,
  },
  {
    title: 'Settle on one error response shape for the whole API',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Code, message, and an optional details object.',
    offsetStart: -228,
    span: 3,
  },
  {
    title: 'Learn request validation at the boundary, and trust nothing inside',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Parse into a typed shape, do not merely check.',
    offsetStart: -224,
    span: 5,
  },
  {
    title: 'Learn pagination: offset versus cursor, and why cursor wins at scale',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Implement both against the same table.',
    offsetStart: -218,
    span: 4,
  },
  {
    title: 'Learn idempotency and make retried writes safe',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Add an idempotency key to one endpoint.',
    offsetStart: -213,
    span: 5,
  },
  {
    title: 'Learn authentication versus authorisation and stop conflating them',
    category: 'Backend',
    status: 'doing',
    priority: 'high',
    estimatedHours: 5,
    note: 'Write down who you are versus what you may do.',
    offsetStart: -207,
    span: 4,
  },
  {
    title: 'Learn password hashing: why bcrypt or argon2 and never a plain digest',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Understand what the work factor is for.',
    offsetStart: -202,
    span: 4,
  },
  {
    title: 'Learn sessions versus JWTs, and the revocation problem',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Be able to argue for either in an interview.',
    offsetStart: -197,
    span: 6,
  },
  {
    title: 'Implement refresh tokens with rotation and reuse detection',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Detect a stolen refresh token being replayed.',
    offsetStart: -190,
    span: 6,
  },
  {
    title: 'Learn OAuth 2 and OIDC well enough to read the spec diagrams',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 10,
    note: 'Implement the authorisation code flow with PKCE.',
    offsetStart: -183,
    span: 8,
  },
  {
    title: 'Learn CORS from the server side and stop guessing at the headers',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Understand the preflight and when it is skipped.',
    offsetStart: -174,
    span: 3,
  },
  {
    title: 'Learn the OWASP Top Ten and check the app against each item',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 10,
    note: 'One concrete finding per category or a written reason there is none.',
    offsetStart: -170,
    span: 8,
  },
  {
    title: 'Learn SQL injection by writing a vulnerable endpoint, then fixing it',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Parameterised queries everywhere afterwards.',
    offsetStart: -161,
    span: 4,
  },
  {
    title: 'Learn rate limiting: token bucket, sliding window, and where to put it',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Return 429 with Retry-After.',
    offsetStart: -156,
    span: 5,
  },
  {
    title: 'Learn structured logging and give every request a correlation id',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Follow one request end to end through the logs.',
    offsetStart: -150,
    span: 4,
  },
  {
    title: 'Learn the difference between logs, metrics and traces',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Know which question each one answers.',
    offsetStart: -145,
    span: 4,
  },
  {
    title: 'Add OpenTelemetry tracing and read a real flame graph',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Find the slowest span in a request you thought was fast.',
    offsetStart: -140,
    span: 7,
  },
  {
    title: 'Learn health checks: liveness versus readiness, and what each should test',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 3,
    note: 'Readiness must check dependencies; liveness must not.',
    offsetStart: -132,
    span: 3,
  },
  {
    title: 'Learn graceful shutdown and stop dropping in-flight requests on deploy',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Handle SIGTERM, drain, then exit.',
    offsetStart: -128,
    span: 4,
  },
  {
    title: 'Learn connection pooling and why the pool size is not just bigger is better',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Load test at three pool sizes.',
    offsetStart: -123,
    span: 4,
  },
  {
    title: 'Learn caching layers and cache invalidation strategies',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Pick TTL, write-through or explicit bust per case.',
    offsetStart: -118,
    span: 7,
  },
  {
    title: 'Learn Redis beyond get and set: sorted sets, expiry, and pipelines',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Build a leaderboard and a rate limiter with it.',
    offsetStart: -110,
    span: 6,
  },
  {
    title: 'Learn background jobs: queues, workers, retries and dead letters',
    category: 'Backend',
    status: 'doing',
    priority: 'high',
    estimatedHours: 9,
    note: 'A job that fails five times must not disappear silently.',
    offsetStart: -103,
    span: 7,
  },
  {
    title: 'Learn exponential backoff with jitter, and why jitter matters',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 3,
    note: 'Simulate a thundering herd with and without it.',
    offsetStart: -95,
    span: 3,
  },
  {
    title: 'Learn the outbox pattern for writing to a database and a queue atomically',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Prove the naive version loses messages.',
    offsetStart: -91,
    span: 6,
  },
  {
    title: 'Learn webhooks: signing, verification, replay protection and retries',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Verify a signature, then reject a replayed body.',
    offsetStart: -84,
    span: 5,
  },
  {
    title: 'Learn file uploads: streaming, size limits and presigned URLs',
    category: 'Backend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Never buffer a whole upload in memory.',
    offsetStart: -78,
    span: 5,
  },
  {
    title: 'Learn server-sent events and WebSockets, and pick per use case',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Build a live counter with each.',
    offsetStart: -72,
    span: 6,
  },
  {
    title: 'Learn API versioning and how to deprecate an endpoint without breaking clients',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Write the deprecation timeline down.',
    offsetStart: -65,
    span: 4,
  },
  {
    title: 'Write an OpenAPI spec and generate a client from it',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Spec first, then make the server match.',
    offsetStart: -60,
    span: 6,
  },
  {
    title: 'Learn GraphQL and the N+1 problem it hands you',
    category: 'Backend',
    status: 'todo',
    priority: 'low',
    estimatedHours: 9,
    note: 'Fix it with a dataloader, then measure.',
    offsetStart: -53,
    span: 7,
  },
  {
    title: 'Learn integration testing against a real database in a container',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'No mocks for the data layer.',
    offsetStart: -45,
    span: 7,
  },
  {
    title: 'Learn contract testing between a service and its consumers',
    category: 'Backend',
    status: 'todo',
    priority: 'low',
    estimatedHours: 6,
    note: 'Break the provider and watch the consumer test fail.',
    offsetStart: -37,
    span: 5,
  },
  {
    title: 'Learn feature flags and how to remove one after it ships',
    category: 'Backend',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'A flag with no removal date is technical debt.',
    offsetStart: -31,
    span: 4,
  },
  {
    title: 'Learn twelve-factor config: environment over files, no secrets in the repo',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Audit the repo history for a committed secret.',
    offsetStart: -26,
    span: 3,
  },
  {
    title: 'Learn timezone and timestamp handling, and store UTC everywhere',
    category: 'Backend',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Reproduce a daylight-saving bug on purpose.',
    offsetStart: -22,
    span: 5,
  },
  {
    title: 'Learn concurrency in the backend language: goroutines or the event loop',
    category: 'Backend',
    status: 'doing',
    priority: 'high',
    estimatedHours: 10,
    note: 'Race two writers on purpose and watch it corrupt.',
    offsetStart: -15,
    span: 16,
  },
  {
    title: 'Learn context propagation, deadlines and cancellation',
    category: 'Backend',
    status: 'doing',
    priority: 'high',
    estimatedHours: 7,
    note: 'Cancel a slow downstream call from the caller.',
    offsetStart: -6,
    span: 15,
  },
  {
    title: 'Learn circuit breakers and bulkheads for failing dependencies',
    category: 'Backend',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Trip the breaker in a test, then let it half-open.',
    offsetStart: -1,
    span: 14,
  },
  {
    title: 'Learn database transactions in the service layer, and where to put the boundary',
    category: 'Backend',
    status: 'todo',
    priority: 'high',
    estimatedHours: 8,
    note: 'One transaction per use case, not per query.',
    offsetStart: 14,
    span: 12,
  },
  {
    title: 'Learn event-driven design: events versus commands, and at-least-once delivery',
    category: 'Backend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 12,
    note: 'Every consumer must be idempotent.',
    offsetStart: 28,
    span: 18,
  },
  {
    title: 'Learn when a monolith should stay a monolith',
    category: 'Backend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Write the argument against splitting this one up.',
    offsetStart: 47,
    span: 8,
  },
  {
    title: 'Learn service boundaries and how data ownership decides them',
    category: 'Backend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 10,
    note: 'Two services must never write the same table.',
    offsetStart: 57,
    span: 14,
  },
  {
    title: 'Learn gRPC and protobuf, and where they beat JSON over HTTP',
    category: 'Backend',
    status: 'todo',
    priority: 'low',
    estimatedHours: 10,
    note: 'Measure payload size and latency against REST.',
    offsetStart: 74,
    span: 14,
  },
  {
    title: 'Learn load testing and find the actual breaking point of one endpoint',
    category: 'Backend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Record p50, p95 and p99, not the average.',
    offsetStart: 92,
    span: 10,
  },
  {
    title: 'Write a runbook for the three most likely production failures',
    category: 'Backend',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Someone else should be able to follow it at 3am.',
    offsetStart: 106,
    span: 8,
  },

  // Infra / Cloud
  {
    title: 'Learn the Linux command line well enough to stop reaching for a GUI',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 10,
    note: 'Pipes, redirection, find, grep, xargs, permissions.',
    offsetStart: -260,
    span: 8,
  },
  {
    title: 'Learn process management: ps, signals, exit codes and orphaned children',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Know what SIGTERM versus SIGKILL means for cleanup.',
    offsetStart: -251,
    span: 4,
  },
  {
    title: 'Learn systemd units well enough to run a service on a bare VM',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Restart policy, logging, and start on boot.',
    offsetStart: -246,
    span: 5,
  },
  {
    title: 'Learn SSH properly: keys, agent forwarding risks, and config aliases',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Passwordless login, and know why agent forwarding is risky.',
    offsetStart: -240,
    span: 3,
  },
  {
    title: 'Learn the difference between an image and a container',
    category: 'Infra / Cloud',
    status: 'doing',
    priority: 'high',
    estimatedHours: 4,
    note: 'The blueprint and the running thing.',
    offsetStart: -236,
    span: 3,
  },
  {
    title: 'Learn Dockerfile layer caching and order the instructions accordingly',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Dependencies before source, always.',
    offsetStart: -232,
    span: 4,
  },
  {
    title: 'Learn multi-stage builds and cut the image size in half',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Record the before and after size.',
    offsetStart: -227,
    span: 4,
  },
  {
    title: 'Learn docker compose for an app plus database plus cache',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'One command to bring the whole stack up.',
    offsetStart: -222,
    span: 5,
  },
  {
    title: 'Learn container networking: bridge, host, and published ports',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Understand why localhost inside a container is not the host.',
    offsetStart: -216,
    span: 4,
  },
  {
    title: 'Learn volumes and bind mounts, and which one survives a rebuild',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Lose data on purpose once.',
    offsetStart: -211,
    span: 3,
  },
  {
    title: 'Stop running containers as root and learn why it matters',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Add a non-root user to every image.',
    offsetStart: -207,
    span: 3,
  },
  {
    title: 'Scan an image for vulnerabilities and fix the findings',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Pin a base image digest rather than a floating tag.',
    offsetStart: -203,
    span: 4,
  },
  {
    title: 'Learn git branching for real: rebase, merge, and when each is right',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Never rebase a branch someone else has pulled.',
    offsetStart: -198,
    span: 5,
  },
  {
    title: 'Learn to recover from git mistakes with reflog',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 3,
    note: 'Delete a branch on purpose, then get it back.',
    offsetStart: -192,
    span: 2,
  },
  {
    title: 'Learn git bisect and find a real regression with it',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Automate it with a test script.',
    offsetStart: -189,
    span: 3,
  },
  {
    title: 'Set up CI that runs lint, type-check and tests on every push',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'A red build must block the merge.',
    offsetStart: -185,
    span: 5,
  },
  {
    title: 'Add caching to CI and cut the pipeline time',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Record the before and after minutes.',
    offsetStart: -179,
    span: 3,
  },
  {
    title: 'Build a deploy pipeline with a manual approval before production',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Staging must be reached automatically, production must not.',
    offsetStart: -175,
    span: 6,
  },
  {
    title: 'Learn blue-green and canary deploys, and pick one to implement',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Include the rollback path, not just the roll forward.',
    offsetStart: -168,
    span: 7,
  },
  {
    title: 'Learn AWS IAM: users, roles, policies, and least privilege',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 10,
    note: 'This is where most exam points are lost.',
    offsetStart: -160,
    span: 8,
  },
  {
    title: 'Build a VPC by hand: subnets, route tables, gateways, security groups',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 12,
    note: 'No wizard. Draw it first, then build it.',
    offsetStart: -151,
    span: 9,
  },
  {
    title: 'Learn the difference between a security group and a network ACL',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 3,
    note: 'Stateful versus stateless.',
    offsetStart: -141,
    span: 2,
  },
  {
    title: 'Deploy something to EC2 by hand before automating it',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Feel the manual pain once so the automation makes sense.',
    offsetStart: -138,
    span: 6,
  },
  {
    title: 'Learn S3: storage classes, lifecycle rules, and how a bucket leaks',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Block public access, then prove it is blocked.',
    offsetStart: -131,
    span: 5,
  },
  {
    title: 'Learn CloudFront and how a CDN interacts with cache headers',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Invalidate a path and watch the origin get hit.',
    offsetStart: -125,
    span: 5,
  },
  {
    title: 'Learn RDS: backups, snapshots, multi-AZ and read replicas',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Restore from a snapshot at least once.',
    offsetStart: -119,
    span: 6,
  },
  {
    title: 'Learn Lambda and where serverless is the wrong answer',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Measure a cold start and decide if it matters.',
    offsetStart: -112,
    span: 7,
  },
  {
    title: 'Learn ECS or Fargate and deploy a container without managing a server',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 10,
    note: 'Task definitions, services, and a load balancer.',
    offsetStart: -104,
    span: 8,
  },
  {
    title: 'Learn Terraform basics: providers, resources, state and plan',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 10,
    note: 'Never apply without reading the plan.',
    offsetStart: -95,
    span: 8,
  },
  {
    title: 'Move the Terraform state to a remote backend with locking',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Local state is a single point of failure.',
    offsetStart: -86,
    span: 4,
  },
  {
    title: 'Learn Terraform modules and refactor the config into two of them',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Copy-paste twice, then extract.',
    offsetStart: -81,
    span: 6,
  },
  {
    title: 'Learn secrets management and get every credential out of the repo',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Rotate one secret end to end.',
    offsetStart: -74,
    span: 5,
  },
  {
    title: 'Learn DNS records in practice: A, CNAME, TXT, and TTL behaviour',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Lower the TTL before a cutover, not during.',
    offsetStart: -68,
    span: 4,
  },
  {
    title: 'Learn TLS certificates: issuance, renewal and chain of trust',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Let an expiry happen in a test environment.',
    offsetStart: -63,
    span: 5,
  },
  {
    title: 'Learn nginx as a reverse proxy: upstreams, timeouts and buffering',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Understand which timeout fires first.',
    offsetStart: -57,
    span: 6,
  },
  {
    title: 'Set up metrics and dashboards for a service that matters',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Rate, errors and duration on one screen.',
    offsetStart: -50,
    span: 7,
  },
  {
    title: 'Write alerts on symptoms rather than causes',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Every alert must be actionable or it gets deleted.',
    offsetStart: -42,
    span: 4,
  },
  {
    title: 'Define SLIs and an SLO for one service, and compute the error budget',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Pick a target you would actually defend.',
    offsetStart: -37,
    span: 5,
  },
  {
    title: 'Learn centralised logging and search a real incident in it',
    category: 'Infra / Cloud',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Find one request across three services.',
    offsetStart: -31,
    span: 5,
  },
  {
    title: 'Run a game day: break something on purpose and practise the recovery',
    category: 'Infra / Cloud',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Time how long it takes to notice.',
    offsetStart: -25,
    span: 5,
  },
  {
    title: 'Learn Kubernetes objects: pod, deployment, service, ingress',
    category: 'Infra / Cloud',
    status: 'doing',
    priority: 'high',
    estimatedHours: 12,
    note: 'Only after Docker feels automatic.',
    offsetStart: -18,
    span: 20,
  },
  {
    title: 'Learn kubectl for debugging: describe, logs, exec, port-forward',
    category: 'Infra / Cloud',
    status: 'doing',
    priority: 'high',
    estimatedHours: 6,
    note: 'Debug a CrashLoopBackOff on purpose.',
    offsetStart: -7,
    span: 16,
  },
  {
    title: 'Learn requests and limits, and what OOMKilled really means',
    category: 'Infra / Cloud',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Set a limit too low and watch it die.',
    offsetStart: -3,
    span: 15,
  },
  {
    title: 'Learn ConfigMaps and Secrets, and how Secrets are only base64',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Encryption at rest is a separate decision.',
    offsetStart: 16,
    span: 8,
  },
  {
    title: 'Learn Helm and package the app as a chart',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 9,
    note: 'Values for the parts that differ per environment.',
    offsetStart: 30,
    span: 14,
  },
  {
    title: 'Learn horizontal pod autoscaling and prove it scales under load',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Watch it scale back down as well.',
    offsetStart: 46,
    span: 10,
  },
  {
    title: 'Learn GitOps and make the cluster state match a repository',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'low',
    estimatedHours: 10,
    note: 'No more kubectl apply from a laptop.',
    offsetStart: 60,
    span: 16,
  },
  {
    title: 'Set up a cost dashboard and find the three biggest line items',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Tag every resource so the report is meaningful.',
    offsetStart: 80,
    span: 8,
  },
  {
    title: 'Write a disaster recovery plan and test the restore',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'high',
    estimatedHours: 10,
    note: 'A backup that has never been restored is not a backup.',
    offsetStart: 95,
    span: 14,
  },
  {
    title: 'Learn infrastructure drift detection and run it on a schedule',
    category: 'Infra / Cloud',
    status: 'todo',
    priority: 'low',
    estimatedHours: 5,
    note: 'Someone will always change something by hand.',
    offsetStart: 118,
    span: 8,
  },

  // Database
  {
    title: 'Learn SELECT, WHERE, ORDER BY and LIMIT until they are reflex',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Fifty queries against a real dataset.',
    offsetStart: -257,
    span: 4,
  },
  {
    title: 'Learn every JOIN type and draw what each one returns',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Inner, left, right, full, cross, and a self join.',
    offsetStart: -252,
    span: 5,
  },
  {
    title: 'Learn GROUP BY and HAVING, and why WHERE cannot filter an aggregate',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Write ten aggregate reports.',
    offsetStart: -246,
    span: 4,
  },
  {
    title: 'Learn NULL semantics and the three-valued logic that follows',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'NOT IN with a NULL will bite you once.',
    offsetStart: -241,
    span: 3,
  },
  {
    title: 'Learn subqueries versus CTEs, and when a CTE is clearer',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Rewrite three nested subqueries as CTEs.',
    offsetStart: -237,
    span: 4,
  },
  {
    title: 'Learn window functions: ROW_NUMBER, RANK, LAG and running totals',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Deduplicate a table with ROW_NUMBER.',
    offsetStart: -232,
    span: 6,
  },
  {
    title: 'Learn UPSERT and the concurrency pitfall it hides',
    category: 'Database',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 4,
    note: 'ON CONFLICT still needs a unique constraint.',
    offsetStart: -225,
    span: 3,
  },
  {
    title: 'Learn primary keys, foreign keys and cascading deletes',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Decide cascade versus restrict deliberately.',
    offsetStart: -221,
    span: 4,
  },
  {
    title: 'Learn constraints as documentation: NOT NULL, UNIQUE, CHECK',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Push every invariant you can into the schema.',
    offsetStart: -216,
    span: 3,
  },
  {
    title: 'Learn normalisation up to third normal form, and when to stop',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Normalise a messy spreadsheet into tables.',
    offsetStart: -212,
    span: 6,
  },
  {
    title: 'Learn deliberate denormalisation and write down the trade you made',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Only with a measurement behind it.',
    offsetStart: -205,
    span: 4,
  },
  {
    title: 'Model a many-to-many relationship with a join table and extra columns',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'The join table usually wants its own attributes.',
    offsetStart: -200,
    span: 4,
  },
  {
    title: 'Learn to read EXPLAIN and make it a reflex before optimising',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Never guess at a slow query again.',
    offsetStart: -195,
    span: 7,
  },
  {
    title: 'Learn EXPLAIN ANALYZE and the gap between estimated and actual rows',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'A bad estimate usually means stale statistics.',
    offsetStart: -187,
    span: 5,
  },
  {
    title: 'Learn how a B-tree index works, and why order matters',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Draw the tree for a small table by hand.',
    offsetStart: -181,
    span: 6,
  },
  {
    title: 'Learn composite indexes and the leftmost prefix rule',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Prove a query skips the index by reordering the columns.',
    offsetStart: -174,
    span: 4,
  },
  {
    title: 'Learn covering indexes and index-only scans',
    category: 'Database',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Turn one heap fetch into an index-only scan.',
    offsetStart: -169,
    span: 4,
  },
  {
    title: 'Learn what kills an index: functions on columns and leading wildcards',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Fix a WHERE that wraps the column in a function.',
    offsetStart: -164,
    span: 3,
  },
  {
    title: 'Learn partial and expression indexes',
    category: 'Database',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Index only the rows a hot query actually reads.',
    offsetStart: -160,
    span: 4,
  },
  {
    title: 'Learn the write cost of an index and remove three unused ones',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Check the index usage statistics first.',
    offsetStart: -155,
    span: 4,
  },
  {
    title: 'Learn transactions and the four isolation levels',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Reproduce a dirty read and a phantom read.',
    offsetStart: -150,
    span: 7,
  },
  {
    title: 'Learn MVCC and why a long transaction blocks vacuum',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Watch table bloat grow while one transaction stays open.',
    offsetStart: -142,
    span: 5,
  },
  {
    title: 'Learn row locks, deadlocks and consistent lock ordering',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Cause a deadlock on purpose, then prevent it.',
    offsetStart: -136,
    span: 5,
  },
  {
    title: 'Learn SELECT FOR UPDATE and optimistic locking, and pick per case',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Implement a version column and a retry.',
    offsetStart: -130,
    span: 4,
  },
  {
    title: 'Learn the N+1 problem by finding one in a real ORM log',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Count the queries before and after the fix.',
    offsetStart: -125,
    span: 4,
  },
  {
    title: 'Learn eager versus lazy loading and the cost of each',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Over-fetching is also a bug.',
    offsetStart: -120,
    span: 4,
  },
  {
    title: 'Learn migrations and write one that is safe to run against live traffic',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Add nullable, backfill, then enforce.',
    offsetStart: -115,
    span: 7,
  },
  {
    title: 'Learn how to rename a column with zero downtime',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Expand, migrate, contract, over three deploys.',
    offsetStart: -107,
    span: 5,
  },
  {
    title: 'Learn why some migrations lock a table and how to avoid it',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Create the index concurrently.',
    offsetStart: -101,
    span: 5,
  },
  {
    title: 'Learn connection limits and what happens when the pool is exhausted',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Exhaust it on purpose and read the error.',
    offsetStart: -95,
    span: 4,
  },
  {
    title: 'Learn backup and restore, and actually restore into a scratch database',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Time the restore, so the RTO is a real number.',
    offsetStart: -90,
    span: 6,
  },
  {
    title: 'Learn point-in-time recovery and what the WAL is for',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Recover to a moment before a bad delete.',
    offsetStart: -83,
    span: 5,
  },
  {
    title: 'Learn read replicas and replication lag, and where lag breaks correctness',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Read your own write from a replica and watch it fail.',
    offsetStart: -77,
    span: 5,
  },
  {
    title: 'Learn full text search in the database before reaching for a search engine',
    category: 'Database',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 7,
    note: 'A GIN index goes a long way.',
    offsetStart: -71,
    span: 6,
  },
  {
    title: 'Learn JSON columns and when they are a schema smell',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'If you always query one key, it wants a column.',
    offsetStart: -64,
    span: 4,
  },
  {
    title: 'Learn table partitioning and pick a sensible partition key',
    category: 'Database',
    status: 'done',
    priority: 'low',
    estimatedHours: 8,
    note: 'Partition a time-series table by month.',
    offsetStart: -59,
    span: 6,
  },
  {
    title: 'Learn database-side data types properly: numeric versus float for money',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Never store money in a float.',
    offsetStart: -52,
    span: 3,
  },
  {
    title: 'Learn timestamptz versus timestamp and store UTC',
    category: 'Database',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Reproduce a daylight-saving off-by-one.',
    offsetStart: -48,
    span: 3,
  },
  {
    title: 'Learn seeding and fixtures so tests start from a known state',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'A test that depends on order is already broken.',
    offsetStart: -44,
    span: 4,
  },
  {
    title: 'Learn soft deletes and the queries they quietly break',
    category: 'Database',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Every query now needs a deleted_at filter.',
    offsetStart: -39,
    span: 3,
  },
  {
    title: 'Learn audit tables and how to record who changed what',
    category: 'Database',
    status: 'todo',
    priority: 'low',
    estimatedHours: 6,
    note: 'A trigger or an application-level log, pick one.',
    offsetStart: -34,
    span: 5,
  },
  {
    title: 'Tune three genuinely slow queries end to end',
    category: 'Database',
    status: 'doing',
    priority: 'high',
    estimatedHours: 12,
    note: 'Measure, change one thing, measure again.',
    offsetStart: -20,
    span: 18,
  },
  {
    title: 'Learn query plan caching and parameter sniffing',
    category: 'Database',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 6,
    note: 'The same query can be fast and slow with different arguments.',
    offsetStart: -8,
    span: 15,
  },
  {
    title: 'Learn when Redis is the wrong tool and a database index is the answer',
    category: 'Database',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Caching a slow query hides the missing index.',
    offsetStart: -2,
    span: 13,
  },
  {
    title: 'Learn document databases and where the schema flexibility actually pays',
    category: 'Database',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 9,
    note: 'Model the same data relationally and as documents.',
    offsetStart: 18,
    span: 14,
  },
  {
    title: 'Learn the CAP theorem well enough to stop misusing it',
    category: 'Database',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 5,
    note: 'It is about partitions, not everyday trade-offs.',
    offsetStart: 34,
    span: 8,
  },
  {
    title: 'Learn eventual consistency and what it means for a read after write',
    category: 'Database',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Design one screen that tolerates stale data.',
    offsetStart: 44,
    span: 12,
  },
  {
    title: 'Learn sharding and why it is a last resort',
    category: 'Database',
    status: 'todo',
    priority: 'low',
    estimatedHours: 10,
    note: 'Exhaust vertical scaling and read replicas first.',
    offsetStart: 58,
    span: 14,
  },
  {
    title: 'Learn a time-series store and where it beats a relational table',
    category: 'Database',
    status: 'todo',
    priority: 'low',
    estimatedHours: 8,
    note: 'Ingest a month of metrics and query it.',
    offsetStart: 76,
    span: 12,
  },
  {
    title: 'Learn a vector index and run one similarity search end to end',
    category: 'Database',
    status: 'todo',
    priority: 'low',
    estimatedHours: 10,
    note: 'Understand recall versus latency before tuning.',
    offsetStart: 100,
    span: 16,
  },

  // CS Fundamentals
  {
    title: 'Learn big-O notation and be able to justify a bound out loud',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'high',
    estimatedHours: 6,
    note: 'Feel the difference between n log n and n squared at a million rows.',
    offsetStart: -259,
    span: 5,
  },
  {
    title: 'Learn arrays versus linked lists and the cache behaviour behind the difference',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Benchmark a traversal of each.',
    offsetStart: -253,
    span: 4,
  },
  {
    title: 'Implement a dynamic array and understand amortised cost',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Doubling is why append is O(1) on average.',
    offsetStart: -248,
    span: 4,
  },
  {
    title: 'Implement a hash map with open addressing and with chaining',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 8,
    note: 'Understand load factor and the cost of a resize.',
    offsetStart: -243,
    span: 6,
  },
  {
    title: 'Learn stacks and queues, and implement both on top of an array',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Then use a stack to validate bracket matching.',
    offsetStart: -236,
    span: 3,
  },
  {
    title: 'Learn binary search and get the boundary conditions right every time',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Write it from scratch without an off-by-one.',
    offsetStart: -232,
    span: 5,
  },
  {
    title: 'Learn binary search on the answer, not just on an array',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Solve a minimise-the-maximum problem with it.',
    offsetStart: -226,
    span: 4,
  },
  {
    title: 'Learn the two pointer technique and recognise when it applies',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Ten problems until the shape is obvious.',
    offsetStart: -221,
    span: 4,
  },
  {
    title: 'Learn the sliding window technique for subarray problems',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Fixed size first, then variable size.',
    offsetStart: -216,
    span: 5,
  },
  {
    title: 'Learn prefix sums and difference arrays',
    category: 'CS Fundamentals',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Turn a range query from O(n) into O(1).',
    offsetStart: -210,
    span: 3,
  },
  {
    title: 'Implement merge sort and quicksort by hand',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Understand stability and the worst case of each.',
    offsetStart: -206,
    span: 6,
  },
  {
    title: 'Learn heaps and implement a priority queue',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Then solve top-k with it.',
    offsetStart: -199,
    span: 5,
  },
  {
    title: 'Learn binary trees: traversals, depth and balance',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Write all three traversals iteratively as well.',
    offsetStart: -193,
    span: 6,
  },
  {
    title: 'Learn binary search trees and what makes one degenerate',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Insert sorted data and watch it become a list.',
    offsetStart: -186,
    span: 5,
  },
  {
    title: 'Learn tries and use one for prefix search',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'low',
    estimatedHours: 5,
    note: 'Compare the memory against a sorted array.',
    offsetStart: -180,
    span: 4,
  },
  {
    title: 'Learn graph representations: adjacency list versus matrix',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Pick based on density, not habit.',
    offsetStart: -175,
    span: 3,
  },
  {
    title: 'Implement breadth-first search and use it for shortest path on an unweighted graph',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'A queue, a visited set, and nothing else.',
    offsetStart: -171,
    span: 5,
  },
  {
    title: 'Implement depth-first search, both recursive and iterative',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Detect a cycle with it.',
    offsetStart: -165,
    span: 5,
  },
  {
    title: 'Learn topological sort and where it shows up in real build systems',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Order a dependency graph.',
    offsetStart: -159,
    span: 4,
  },
  {
    title: "Learn Dijkstra's algorithm and why it needs non-negative weights",
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Implement it with a priority queue.',
    offsetStart: -154,
    span: 6,
  },
  {
    title: 'Learn union-find with path compression',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Use it to detect connected components.',
    offsetStart: -147,
    span: 4,
  },
  {
    title: 'Learn recursion properly: base case, progress, and the call stack',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Trace one call stack on paper.',
    offsetStart: -142,
    span: 5,
  },
  {
    title: 'Learn memoisation and turn an exponential recursion into a linear one',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Fibonacci first, then something real.',
    offsetStart: -136,
    span: 5,
  },
  {
    title: 'Learn dynamic programming: state, transition and order of evaluation',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'high',
    estimatedHours: 12,
    note: 'Define the state before writing any code.',
    offsetStart: -130,
    span: 10,
  },
  {
    title: 'Work the classic DP problems: knapsack, edit distance, longest common subsequence',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 12,
    note: 'Draw the table by hand for a small input.',
    offsetStart: -119,
    span: 10,
  },
  {
    title: 'Learn greedy algorithms and how to tell when greedy is actually correct',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Find a case where the obvious greedy fails.',
    offsetStart: -108,
    span: 5,
  },
  {
    title: 'Learn backtracking with N-queens and a sudoku solver',
    category: 'CS Fundamentals',
    status: 'doing',
    priority: 'low',
    estimatedHours: 8,
    note: 'Prune early or it will never finish.',
    offsetStart: -102,
    span: 6,
  },
  {
    title: 'Learn bit manipulation basics and where it is genuinely useful',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'low',
    estimatedHours: 5,
    note: 'Masks, shifts, and counting set bits.',
    offsetStart: -95,
    span: 4,
  },
  {
    title: 'Learn how integers and floats are actually represented',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Understand why 0.1 plus 0.2 is not 0.3.',
    offsetStart: -90,
    span: 4,
  },
  {
    title: 'Learn character encodings: ASCII, UTF-8, and what a code point is',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 5,
    note: 'Reverse a string with emoji in it and see it break.',
    offsetStart: -85,
    span: 4,
  },
  {
    title: 'Learn processes versus threads and what each one owns',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Memory is shared between threads, not processes.',
    offsetStart: -80,
    span: 5,
  },
  {
    title: 'Learn race conditions by writing one, then fixing it with a lock',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Two threads incrementing the same counter.',
    offsetStart: -74,
    span: 6,
  },
  {
    title: 'Learn deadlock: the four conditions and how to break one',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Consistent lock ordering solves most of them.',
    offsetStart: -67,
    span: 4,
  },
  {
    title: 'Learn virtual memory, paging and what a page fault costs',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Understand why swapping destroys latency.',
    offsetStart: -62,
    span: 5,
  },
  {
    title: 'Learn the memory hierarchy and cache locality',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Benchmark row-major versus column-major traversal.',
    offsetStart: -56,
    span: 4,
  },
  {
    title: 'Learn how a filesystem stores a file: inodes, blocks and directories',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'low',
    estimatedHours: 5,
    note: 'Understand what a hard link really is.',
    offsetStart: -51,
    span: 4,
  },
  {
    title: 'Learn the OSI and TCP/IP models well enough to place any protocol',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Name one protocol per layer.',
    offsetStart: -46,
    span: 4,
  },
  {
    title: 'Learn the TCP handshake, flow control and congestion control',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 7,
    note: 'Understand why a round trip is your latency floor.',
    offsetStart: -41,
    span: 6,
  },
  {
    title: 'Learn what TLS actually does: key exchange, certificates, and the handshake cost',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Read a real handshake in a packet capture.',
    offsetStart: -34,
    span: 5,
  },
  {
    title: 'Learn DNS resolution end to end, from stub resolver to authoritative server',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'Trace one lookup with dig.',
    offsetStart: -28,
    span: 4,
  },
  {
    title: 'Learn hashing versus encryption versus encoding, and stop mixing them up',
    category: 'CS Fundamentals',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'Base64 is not security.',
    offsetStart: -23,
    span: 3,
  },
  {
    title: 'Learn symmetric versus asymmetric cryptography at a working level',
    category: 'CS Fundamentals',
    status: 'doing',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Enough to use a library correctly, not to write one.',
    offsetStart: -14,
    span: 16,
  },
  {
    title: 'Do a daily algorithm problem with a 25 minute timer',
    category: 'CS Fundamentals',
    status: 'doing',
    priority: 'low',
    estimatedHours: 40,
    note: 'Read the solution when time is up, no guilt.',
    offsetStart: -12,
    span: 120,
  },
  {
    title: 'Learn how a compiler works: lexing, parsing, and an AST',
    category: 'CS Fundamentals',
    status: 'doing',
    priority: 'low',
    estimatedHours: 12,
    note: 'Write a calculator parser by hand.',
    offsetStart: -5,
    span: 20,
  },
  {
    title: 'Learn garbage collection and what a stop-the-world pause costs',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Generational collection and why most objects die young.',
    offsetStart: 20,
    span: 12,
  },
  {
    title: 'Learn the actor model and message passing as an alternative to locks',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'low',
    estimatedHours: 8,
    note: 'Share memory by communicating, not the reverse.',
    offsetStart: 36,
    span: 12,
  },
  {
    title: 'Learn consensus at a conceptual level: quorum, leader election, split brain',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 10,
    note: 'Enough to reason about a cluster, not to implement Raft.',
    offsetStart: 52,
    span: 16,
  },
  {
    title: 'Learn idempotency and exactly-once as a distributed systems problem',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Exactly-once delivery does not exist; exactly-once effect does.',
    offsetStart: 70,
    span: 12,
  },
  {
    title: 'Learn regular expressions properly, including catastrophic backtracking',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 6,
    note: 'Write one that hangs on a crafted input.',
    offsetStart: 86,
    span: 10,
  },
  {
    title: 'Learn the theory behind property-based testing and try it on a parser',
    category: 'CS Fundamentals',
    status: 'todo',
    priority: 'low',
    estimatedHours: 8,
    note: 'Generators find the cases you would never write.',
    offsetStart: 112,
    span: 14,
  },

  // Certification
  {
    title: 'Decide which certifications are worth the time this year',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 3,
    note: 'A certificate is a deadline, not a substitute for experience.',
    offsetStart: -255,
    span: 3,
  },
  {
    title: 'Book the first exam so the date is fixed and cannot slip',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 1,
    note: 'Nothing focuses study like a paid booking.',
    offsetStart: -251,
    span: 1,
  },
  {
    title: 'Take a diagnostic practice exam before studying anything',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 3,
    note: 'A baseline score tells you where to spend the hours.',
    offsetStart: -249,
    span: 2,
  },
  {
    title: 'Read the AWS Cloud Practitioner exam guide and map the domains',
    category: 'Certification',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 2,
    note: 'Weight the study time by the domain percentages.',
    offsetStart: -246,
    span: 2,
  },
  {
    title: 'Study the AWS shared responsibility model until it is automatic',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 4,
    note: 'It appears in almost every AWS exam.',
    offsetStart: -243,
    span: 3,
  },
  {
    title: 'Study AWS core services: EC2, S3, RDS, VPC, IAM',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 12,
    note: 'Know what each is for before knowing the options.',
    offsetStart: -239,
    span: 9,
  },
  {
    title: 'Study AWS billing, support plans and the pricing models',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 5,
    note: 'On-demand, reserved, spot, savings plans.',
    offsetStart: -229,
    span: 4,
  },
  {
    title: 'Run two AWS Cloud Practitioner practice exams and keep a mistake list',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'One page of mistakes, reviewed the morning of the exam.',
    offsetStart: -224,
    span: 5,
  },
  {
    title: 'Sit the AWS Cloud Practitioner exam',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 2,
    note: 'Arrive early; read every question twice.',
    offsetStart: -218,
    span: 1,
  },
  {
    title: 'Read the AWS Solutions Architect Associate exam guide and plan the weeks',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 3,
    note: 'Considerably deeper than the practitioner exam.',
    offsetStart: -215,
    span: 2,
  },
  {
    title: 'Study VPC design in depth: subnets, NAT, peering, endpoints',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 14,
    note: 'Draw every architecture before reading the answer.',
    offsetStart: -211,
    span: 11,
  },
  {
    title: 'Study IAM in depth: policies, roles, trust relationships, permission boundaries',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 12,
    note: 'This is where the practice scores drop.',
    offsetStart: -199,
    span: 10,
  },
  {
    title: 'Study S3 in depth: storage classes, lifecycle, replication, encryption',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 10,
    note: 'Know which class fits which access pattern.',
    offsetStart: -188,
    span: 8,
  },
  {
    title: 'Study high availability patterns: multi-AZ, multi-region, failover',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 10,
    note: 'Know the RTO and RPO of each pattern.',
    offsetStart: -179,
    span: 8,
  },
  {
    title: 'Study load balancing and auto scaling in depth',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 9,
    note: 'ALB versus NLB, target groups, health checks.',
    offsetStart: -170,
    span: 7,
  },
  {
    title: 'Study AWS database options and when each is the right answer',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 10,
    note: 'RDS, Aurora, DynamoDB, ElastiCache, Redshift.',
    offsetStart: -162,
    span: 8,
  },
  {
    title: 'Study decoupling services: SQS, SNS, EventBridge, Step Functions',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 9,
    note: 'Queue versus topic versus bus, decided quickly.',
    offsetStart: -153,
    span: 7,
  },
  {
    title: 'Study AWS monitoring: CloudWatch, CloudTrail, Config',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 7,
    note: 'Which one answers which question.',
    offsetStart: -145,
    span: 6,
  },
  {
    title: 'Study AWS cost optimisation scenarios',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 6,
    note: 'The cheapest answer that still meets the requirement wins.',
    offsetStart: -138,
    span: 5,
  },
  {
    title: 'Run four AWS Solutions Architect practice exams under real timing',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 12,
    note: 'No pausing, no looking things up.',
    offsetStart: -132,
    span: 9,
  },
  {
    title: 'Review every wrong answer and write down why the right one was right',
    category: 'Certification',
    status: 'doing',
    priority: 'high',
    estimatedHours: 8,
    note: 'The reason matters more than the answer.',
    offsetStart: -122,
    span: 6,
  },
  {
    title: 'Sit the AWS Solutions Architect Associate exam',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 3,
    note: 'Flag and move on rather than stalling on one question.',
    offsetStart: -115,
    span: 1,
  },
  {
    title: 'Read the 基本情報技術者 syllabus and map it to what is already known',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 4,
    note: 'Much of the CS fundamentals work already covers it.',
    offsetStart: -112,
    span: 3,
  },
  {
    title: 'Study the discrete maths and base conversion section',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Binary, hex, logic gates, boolean algebra.',
    offsetStart: -108,
    span: 7,
  },
  {
    title: 'Study the hardware and computer architecture section',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 8,
    note: 'CPU, memory hierarchy, interrupts, I/O.',
    offsetStart: -100,
    span: 7,
  },
  {
    title: 'Study the project management and strategy sections',
    category: 'Certification',
    status: 'todo',
    priority: 'low',
    estimatedHours: 9,
    note: 'The least interesting part; do it early while motivation lasts.',
    offsetStart: -92,
    span: 8,
  },
  {
    title: 'Work ten years of past questions for the morning paper',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 20,
    note: 'Past questions repeat more than anyone admits.',
    offsetStart: -83,
    span: 14,
  },
  {
    title: 'Work the afternoon paper algorithm section repeatedly',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 16,
    note: 'Trace the pseudocode by hand every time.',
    offsetStart: -68,
    span: 12,
  },
  {
    title: 'Sit the 基本情報技術者 exam',
    category: 'Certification',
    status: 'done',
    priority: 'high',
    estimatedHours: 6,
    note: 'Both papers in one day; pace accordingly.',
    offsetStart: -55,
    span: 1,
  },
  {
    title: 'Study for the AWS Developer Associate: deployment and CI/CD domains',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 12,
    note: 'CodePipeline, CodeBuild, CodeDeploy.',
    offsetStart: -52,
    span: 10,
  },
  {
    title: 'Study Lambda, API Gateway and DynamoDB at exam depth',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 12,
    note: 'Partition key design comes up repeatedly.',
    offsetStart: -41,
    span: 9,
  },
  {
    title: 'Run three AWS Developer Associate practice exams',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 9,
    note: 'Target 85 percent before booking.',
    offsetStart: -31,
    span: 7,
  },
  {
    title: 'Sit the AWS Developer Associate exam',
    category: 'Certification',
    status: 'done',
    priority: 'mid',
    estimatedHours: 3,
    note: 'Third AWS exam; the format should feel routine now.',
    offsetStart: -23,
    span: 1,
  },
  {
    title: 'Book the 応用情報技術者 exam and work back from the date',
    category: 'Certification',
    status: 'doing',
    priority: 'high',
    estimatedHours: 2,
    note: 'The descriptive afternoon paper needs a longer runway.',
    offsetStart: -19,
    span: 20,
  },
  {
    title: 'Work through the 応用情報 morning paper past questions',
    category: 'Certification',
    status: 'doing',
    priority: 'high',
    estimatedHours: 30,
    note: 'Two sets a week, timed.',
    offsetStart: -10,
    span: 60,
  },
  {
    title: 'Practise the 応用情報 afternoon descriptive answers',
    category: 'Certification',
    status: 'doing',
    priority: 'high',
    estimatedHours: 24,
    note: 'Writing concisely under time is the actual skill.',
    offsetStart: -4,
    span: 70,
  },
  {
    title: 'Study for the Certified Kubernetes Application Developer exam',
    category: 'Certification',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 25,
    note: 'Hands-on and timed; speed with kubectl is the differentiator.',
    offsetStart: 22,
    span: 30,
  },
  {
    title: 'Drill kubectl imperative commands until they are muscle memory',
    category: 'Certification',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 12,
    note: 'There is no time to write YAML from scratch in the exam.',
    offsetStart: 40,
    span: 20,
  },
  {
    title: 'Set up vim and shell aliases for the CKAD exam environment',
    category: 'Certification',
    status: 'todo',
    priority: 'low',
    estimatedHours: 3,
    note: 'Minutes saved on setup are minutes spent on questions.',
    offsetStart: 56,
    span: 5,
  },
  {
    title: 'Run two CKAD mock exams under strict time',
    category: 'Certification',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 8,
    note: 'Skip anything that stalls for more than four minutes.',
    offsetStart: 64,
    span: 10,
  },
  {
    title: 'Sit the CKAD exam',
    category: 'Certification',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 3,
    note: 'One free retake is included; use it if needed.',
    offsetStart: 78,
    span: 1,
  },
  {
    title: 'Study for the Terraform Associate certification',
    category: 'Certification',
    status: 'todo',
    priority: 'low',
    estimatedHours: 15,
    note: 'Mostly consolidates the infrastructure work already done.',
    offsetStart: 82,
    span: 20,
  },
  {
    title: 'Sit the Terraform Associate exam',
    category: 'Certification',
    status: 'todo',
    priority: 'low',
    estimatedHours: 2,
    note: 'Shorter and cheaper than the AWS exams.',
    offsetStart: 104,
    span: 1,
  },
  {
    title: 'Study for the AWS Solutions Architect Professional exam',
    category: 'Certification',
    status: 'todo',
    priority: 'high',
    estimatedHours: 45,
    note: 'A significant step up; long scenario questions.',
    offsetStart: 108,
    span: 55,
  },
  {
    title: 'Study advanced AWS networking: Transit Gateway, Direct Connect, hybrid DNS',
    category: 'Certification',
    status: 'todo',
    priority: 'high',
    estimatedHours: 18,
    note: 'The professional exam leans hard on networking.',
    offsetStart: 120,
    span: 30,
  },
  {
    title: 'Study AWS multi-account strategy: Organizations, Control Tower, SCPs',
    category: 'Certification',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 14,
    note: 'Landing zone design shows up constantly.',
    offsetStart: 145,
    span: 24,
  },
  {
    title: 'Study migration strategies and the seven Rs',
    category: 'Certification',
    status: 'todo',
    priority: 'mid',
    estimatedHours: 10,
    note: 'Rehost, replatform, refactor, and the rest.',
    offsetStart: 162,
    span: 16,
  },
  {
    title: 'Run three professional-level practice exams',
    category: 'Certification',
    status: 'todo',
    priority: 'high',
    estimatedHours: 12,
    note: 'Three hours each; build the stamina deliberately.',
    offsetStart: 176,
    span: 14,
  },
  {
    title: 'Sit the AWS Solutions Architect Professional exam',
    category: 'Certification',
    status: 'todo',
    priority: 'high',
    estimatedHours: 4,
    note: 'The longest exam of the set.',
    offsetStart: 192,
    span: 1,
  },
  {
    title: 'Write up what each certification actually changed about the work',
    category: 'Certification',
    status: 'todo',
    priority: 'low',
    estimatedHours: 3,
    note: 'Honest notes, including the ones that changed nothing.',
    offsetStart: 196,
    span: 6,
  },
]
